kind: pipeline
name: openwrt_ci

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&compile
    image: ubuntu:latest
    environment:
      id:
        from_secret: id
      ss:
        from_secret: ss
      token:
        from_secret: token
    commands:  
      - bash .build.sh
