kind: pipeline
name: openwrt_ci

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&compile for ax3600
    image: ubuntu:latest
    environment:
      id:
        from_secret: id
      ss:
        from_secret: ss
    commands:
      - bash .build-c.sh

  - name: setup&compile for ax6
    image: ubuntu:latest
    environment:
      id:
        from_secret: id
      ss:
        from_secret: ss
    commands:
      - bash .build-d.sh
